---
title: Sam Anderson
timezone: UTC
collections:
  archive:
    title: Writing
    output: true
    permalink: "/writing/:path/"
defaults:
- scope:
    path: ''
    type: archive
  values:
    Image:
    Publication:
    Source: http://google.com
