---
title: Sam Anderson
timezone: UTC
collections:
  articles:
    title: Articles
    output: true
    permalink: "/articles/:path/"
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: archive
  values:
    Image: 
    Publication: 
    Source: http://google.com
plugins:
- jekyll-paginate
paginate: 10
paginate_path: "/writing/page:num"
