---
title: Sam Anderson
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: posts
  values:
    image: 
    source: http://nymag.com/
plugins:
- jekyll-paginate
paginate: 15
paginate_path: "/writing/page:num"
